version: '3.8'

services:
  bikes-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bikes-app-front
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
